//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salleSport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adherent
    {
        public int idAdh { get; set; }
        public string nomAdh { get; set; }
        public string prenomAdh { get; set; }
        public string adress { get; set; }
        public string telephone { get; set; }
        public string sexe { get; set; }
        public Nullable<System.DateTime> dateInscription { get; set; }
        public Nullable<System.DateTime> datePayement { get; set; }
        public Nullable<System.DateTime> dateNextPayement { get; set; }
        public Nullable<bool> etatPyement { get; set; }
        public byte[] pic { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> dejatDesactiver { get; set; }
        public Nullable<bool> gym { get; set; }
        public string sportCatg { get; set; }
        public string remarque { get; set; }
        public Nullable<int> reste { get; set; }
    }
}
