//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salleSport
{
    using System;
    using System.Collections.Generic;
    
    public partial class benifice
    {
        public int id { get; set; }
        public string NumFacture { get; set; }
        public Nullable<System.DateTime> datepayement { get; set; }
        public Nullable<double> somme { get; set; }
        public string matriculeAdh { get; set; }
    }
}
